-- 032 — the rest of oauth.db: the media quota ledger and the town log
--       (POS-271, w41, 2026-09-29: "it also holds the media ledger and the town
--       log; they move too")
--
-- ── WHAT MOVES ──────────────────────────────────────────────────────────────
--
--   oauth.db  media         -> office_media         (the quota ledger)
--             town_journal  -> office_town_journal  (the town's input log)
--             meta          -> office_meta          (the town log's drain cursor)
--
-- Same rule as 031: column for column, nothing reshaped, because the import
-- compares every row with its source.
--
--   · `payload` stays `text`. The drain parses it; jsonb would re-sort its keys
--     and a copied row would be unequal to its source.
--   · `gh_id` and `cosigned_gh_id` on the town log are TEXT in the file (the log
--     stores them as strings on purpose: "the drain must be able to judge a row
--     long after the credential that wrote it is gone"), so they stay text.
--   · `seq` is an identity. The import keeps the file's seqs and moves the
--     sequence past them, so the drain cursor in office_meta still names the
--     same row.
--   · `media.created` is epoch MILLISECONDS (media.mjs writes Date.now()),
--     `bytes` a byte count: bigint both.
--
-- ── WHO HOLDS WHAT ──────────────────────────────────────────────────────────
--
-- `office_api` alone, and only the statements the office runs today:
--
--   office_media         SELECT INSERT          (append-only: "nothing here deletes", media.mjs)
--   office_town_journal  SELECT INSERT          (a door appends; the drain reads past a cursor and never deletes)
--   office_meta          SELECT INSERT UPDATE   (the cursor is upserted at the end of a crossing)
--
-- RLS on all three, one policy TO office_api, as 031. The town log holds rows
-- that are not yet the record (a letter before it sails), so it is not the
-- notary's to export either.
--
-- ── IDEMPOTENT. APPLY AS `world2_owner` ─────────────────────────────────────
--
--   sudo -n -u postgres psql -v ON_ERROR_STOP=1 -d world2_dev \
--     -c "SET ROLE world2_owner;" -f world2/schema/032_office_ledgers.sql
--
-- CONSUMERS, named: src/paperwork.mjs, behind OFFICE_PAPERWORK_STORE=1. Behind
-- it: media.mjs and household-media.mjs (the ledger), town-journal.mjs and its
-- readers (town-mail, town-updates, paper-fresh, declare, residency, the drain
-- and the bridge). world2/tools/paperwork-import.mjs writes and compares.

BEGIN;

CREATE TABLE IF NOT EXISTS office_media (
  household   text NOT NULL,
  sha         text NOT NULL,
  ext         text NOT NULL,
  bytes       bigint NOT NULL,
  by_handle   text NOT NULL,
  created     bigint NOT NULL,
  PRIMARY KEY (household, sha)
);

CREATE TABLE IF NOT EXISTS office_town_journal (
  seq             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class           text NOT NULL,
  act             text NOT NULL,
  household       text NOT NULL,
  handle          text,
  gh_id           text,
  gh_login        text,
  cosigned_gh_id  text,
  payload         text,
  written_at      text NOT NULL,
  channel         text
);
CREATE INDEX IF NOT EXISTS office_town_journal_handle ON office_town_journal (handle, seq);
CREATE INDEX IF NOT EXISTS office_town_journal_household ON office_town_journal (household, seq);

CREATE TABLE IF NOT EXISTS office_meta (
  key     text PRIMARY KEY,
  value   text
);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['office_media','office_town_journal','office_meta'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = t AND policyname = t || '_office') THEN
      EXECUTE format('CREATE POLICY %I ON %I TO office_api USING (true) WITH CHECK (true)', t || '_office', t);
    END IF;
  END LOOP;
END $$;

GRANT SELECT, INSERT         ON office_media        TO office_api;
GRANT SELECT, INSERT         ON office_town_journal TO office_api;
GRANT SELECT, INSERT, UPDATE ON office_meta         TO office_api;
GRANT USAGE ON SEQUENCE office_town_journal_seq_seq TO office_api;

INSERT INTO registry (object, kind, owner_pen, consumers, ruling) VALUES
  ('office_media',        'source', 'office_api', '{}', 'POS-271 (2026-09-29): oauth.db moves into the store; the media quota ledger, byte-accounting, never record'),
  ('office_town_journal', 'source', 'office_api', '{}', 'POS-271 (2026-09-29): oauth.db moves into the store; the town log, drained into the record at the crossing'),
  ('office_meta',         'source', 'office_api', '{}', 'POS-271 (2026-09-29): oauth.db moves into the store; the town log''s drain cursor')
ON CONFLICT (object) DO NOTHING;

COMMIT;
